version: "3"

services:

  client:
    container_name: milo.client
    build:
      context: ./client
      dockerfile: Dockerfile_dev
    networks: [default]
    ports: [8010:4200]
    stop_signal: SIGKILL
    volumes:
      - ./client/:/app

  server:
    container_name: milo.server
    build:
      context: ./server
    networks: [default]
    ports: [8011:80]
    restart: unless-stopped
    volumes:
      - ./server/.storage:/data/media
      - ./server/src/main/resources/credentials:/data/credentials
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - MILO_DB_HOST=server-db
      - MILO_DB_NAME=milo
      - MILO_DB_PASS=milo
      - MILO_DB_PORT=3306
      - MILO_DB_USER=root
      - MILO_HOST=http://localhost:8011
      - MILO_MAIL_FROM=info@codeschluss.de
      - MILO_MAIL_RCPT=error@codeschluss.de
      - MILO_MAIL_HOST=mail
      - MILO_MAIL_PORT=1025
      - MILO_MAIL_USER=
      - MILO_MAIL_PASS=
      - MILO_PORTAL_NAME=Milo
      - MILO_PUSH_SECRET=file:/data/credentials/firebase-credentials.json
      - MILO_STORAGE_LOCATION=/data/media
      - MILO_TRANSLATIONS_HOST=translation-api
      - MILO_TRANSLATIONS_PORT=80

  server-db:
    container_name: milo.db
    image: mysql:5
    networks: [default]
    ports: [8012:3306]
    stop_signal: SIGKILL
    restart: unless-stopped
    volumes:
      - milo-db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=milo
      - MYSQL_DATABASE=milo

  mail:
    container_name: milo.mail
    image: maildev/maildev
    networks: [default]
    ports:
      - "8013:1080"
      - "8014:1025"
    stop_signal: SIGKILL

  translation-api:
    container_name: milo.translation-api
    image: easynmt/api:2.0-cpu
    networks: [default]
    ports: [8015:80]
    stop_signal: SIGKILL
    restart: unless-stopped
    volumes:
      - milo-translation-api:/cache
    environment:
      - EASYNMT_MODEL=m2m_100_418M
      - MAX_WORKERS_BACKEND=2
      - MAX_WORKERS_FRONTEND=4
      - EASYNMT_BATCH_SIZE=32
      - TIMEOUT=360


volumes:
  milo-db:
    driver: local
  milo-translation-api:
    driver: local
