version: "3"

services:

  client:
    container_name: wooportal.client
    build:
      context: ./client
      dockerfile: Dockerfile_dev
    networks: [default]
    ports: [8010:4200]
    stop_signal: SIGKILL
    volumes:
      - ./client/:/app

  server:
    container_name: wooportal.server
    build:
      context: ./server
    networks: [default]
    ports: [8011:80]
    restart: unless-stopped
    volumes:
      - ./server/.storage:/data/media
      - ./server/src/main/resources/credentials:/data/credentials
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - WOOPORTAL_DB_HOST=server-db
      - WOOPORTAL_DB_NAME=wooportal
      - WOOPORTAL_DB_PASS=wooportal
      - WOOPORTAL_DB_PORT=3306
      - WOOPORTAL_DB_USER=root
      - WOOPORTAL_HOST=localhost:3000
      - WOOPORTAL_MAIL_FROM=info@codeschluss.de
      - WOOPORTAL_MAIL_RCPT=error@codeschluss.de
      - WOOPORTAL_MAIL_HOST=mail
      - WOOPORTAL_MAIL_PORT=1025
      - WOOPORTAL_MAIL_USER=
      - WOOPORTAL_MAIL_PASS=
      - WOOPORTAL_PORTAL_NAME=Wooportal
      - WOOPORTAL_PUSH_SECRET=file:/data/credentials/firebase-credentials.json
      - WOOPORTAL_STORAGE_LOCATION=/data/media
      - WOOPORTAL_TRANSLATIONS_HOST=translation-api
      - WOOPORTAL_TRANSLATIONS_PORT=80

  server-db:
    container_name: wooportal.db
    image: mysql:5
    networks: [default]
    ports: [8012:3306]
    stop_signal: SIGKILL
    restart: unless-stopped
    volumes:
      - wooportal-db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=wooportal
      - MYSQL_DATABASE=wooportal

  mail:
    container_name: wooportal.mail
    image: maildev/maildev
    networks: [default]
    ports:
      - "8013:1080"
      - "8014:1025"
    stop_signal: SIGKILL

  translation-api:
    container_name: wooportal.translation-api
    image: easynmt/api:2.0-cpu
    networks: [default]
    ports: [8015:80]
    stop_signal: SIGKILL
    restart: unless-stopped
    volumes:
      - wooportal-translation-api:/cache
    environment:
      - EASYNMT_MODEL=m2m_100_418M
      - MAX_WORKERS_BACKEND=2
      - MAX_WORKERS_FRONTEND=4
      - EASYNMT_BATCH_SIZE=32
      - TIMEOUT=360


volumes:
  wooportal-db:
    driver: local
  wooportal-translation-api:
    driver: local
